### ISSUE TITLE
Panic in log

### ISSUE THREAD

**Issue by webfrank** [Tochemey/goakt#578]
**Bug description**
Panic in log

**How to reproduce it?**
Testing node failure and cluster rebalance, no straight instructions to reproduce

**Expected behavior**
No panic

**Screenshots**

**Library Version:**
 - Go-Akt version: 2.10.1
 - Go version: 1.23

**Additional context**
```
node3-1  | {"level":"error","ts":"2024-12-20T14:01:40Z","msg":"failed to synchronize peer=(172.19.0.4:3320): failed to sync peer=(172.19.0.4:3320) request: deadline exceeded"}
node3-1  | {"level":"panic","ts":"2024-12-20T14:01:40Z","msg":"failed to sync peer=(172.19.0.4:3320) request: deadline exceeded"}
node3-1  | panic: failed to sync peer=(172.19.0.4:3320) request: deadline exceeded
node3-1  | 
node3-1  | goroutine 90 [running]:
node3-1  | go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0xc0001d48d0?, {0x0?, 0x0?, 0xc0001a2c00?})
node3-1  | 	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x54
node3-1  | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000201110, {0x0, 0x0, 0x0})
node3-1  | 	/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x24e
node3-1  | go.uber.org/zap.(*Logger).Panic(0xc0002bc200?, {0xc00023c140?, 0x1?}, {0x0, 0x0, 0x0})
node3-1  | 	/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:285 +0x51
node3-1  | github.com/tochemey/goakt/v2/log.(*Log).Panic(0xc0000f0880, {0xc0002bc200?, 0x13a5e20?, 0xc0002e3180?})
node3-1  | 	/go/pkg/mod/github.com/tochemey/goakt/v2@v2.10.1/log/log.go:139 +0x76
node3-1  | github.com/tochemey/goakt/v2/actors.(*actorSystem).replicationLoop(0xc0000ef1e0)
node3-1  | 	/go/pkg/mod/github.com/tochemey/goakt/v2@v2.10.1/actors/actor_system.go:1360 +0x178
node3-1  | created by github.com/tochemey/goakt/v2/actors.(*actorSystem).enableClustering in goroutine 1
node3-1  | 	/go/pkg/mod/github.com/tochemey/goakt/v2@v2.10.1/actors/actor_system.go:1300 +0xa45
```

**Comment by Tochemey** [comment]
@webfrank this is not a bug. peer synchronization failed and the expected behavior is to panic. This is expected. There is a context deadline issue.

**Comment by Tochemey** [comment]
@webfrank this happens when we are replicating an actor in the cluster and it fails https://github.com/Tochemey/goakt/blob/main/actors/actor_system.go#L1360
